'use client'

import { useState } from 'react'
import { Button } from '@/components/ui/button'
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog'

interface AnalysisData {
  sessionTitle: string
  createdAt: string
  objectiveScore: number
  summary: string
  assumptions: { content: string; section: string }[]
  evidenceBacked: { content: string; section: string; evidence_summary: string }[]
  validationRecommendations: {
    item: string
    confidence: string
    reason: string
    method: string
    questions: string[]
  }[]
  constraintAnalysis: { constraint: string; status: string; notes: string }[]
  checklistReview: { item: string; status: string; notes: string }[]
}

interface ExportAnalysisButtonProps {
  analysis: AnalysisData
}

export function ExportAnalysisButton({ analysis }: ExportAnalysisButtonProps) {
  const [showDialog, setShowDialog] = useState(false)
  const [copied, setCopied] = useState(false)

  const generateMarkdown = () => {
    const lines: string[] = []

    lines.push(`# Discovery Session Analysis: ${analysis.sessionTitle}`)
    lines.push(``)
    lines.push(`**Date:** ${new Date(analysis.createdAt).toLocaleString()}`)
    lines.push(``)

    // Objective Score
    lines.push(`## Objective Score: ${analysis.objectiveScore}/100`)
    lines.push(``)
    lines.push(analysis.summary)
    lines.push(``)

    // Assumption Mapping
    lines.push(`## Assumption Mapping`)
    lines.push(``)

    if (analysis.evidenceBacked.length > 0) {
      lines.push(`### Evidence-Backed Items (${analysis.evidenceBacked.length})`)
      lines.push(``)
      analysis.evidenceBacked.forEach((item) => {
        lines.push(`- **${item.content}** (${item.section})`)
        if (item.evidence_summary) {
          lines.push(`  - Evidence: ${item.evidence_summary}`)
        }
      })
      lines.push(``)
    }

    if (analysis.assumptions.length > 0) {
      lines.push(`### Unvalidated Assumptions (${analysis.assumptions.length})`)
      lines.push(``)
      analysis.assumptions.forEach((item) => {
        lines.push(`- **${item.content}** (${item.section})`)
      })
      lines.push(``)
    }

    // Validation Recommendations
    if (analysis.validationRecommendations.length > 0) {
      lines.push(`## Validation Recommendations`)
      lines.push(``)
      analysis.validationRecommendations.forEach((rec, i) => {
        lines.push(`### ${i + 1}. ${rec.item}`)
        lines.push(``)
        lines.push(`- **Confidence:** ${rec.confidence}`)
        lines.push(`- **Why:** ${rec.reason}`)
        lines.push(`- **Method:** ${rec.method}`)
        if (rec.questions && rec.questions.length > 0) {
          lines.push(`- **Questions to answer:**`)
          rec.questions.forEach((q) => {
            lines.push(`  - ${q}`)
          })
        }
        lines.push(``)
      })
    }

    // Constraint Analysis
    if (analysis.constraintAnalysis.length > 0) {
      lines.push(`## Constraint Alignment`)
      lines.push(``)
      lines.push(`| Constraint | Status | Notes |`)
      lines.push(`|------------|--------|-------|`)
      analysis.constraintAnalysis.forEach((item) => {
        lines.push(`| ${item.constraint} | ${item.status} | ${item.notes} |`)
      })
      lines.push(``)
    }

    // Checklist Review
    if (analysis.checklistReview.length > 0) {
      lines.push(`## Checklist Review`)
      lines.push(``)
      lines.push(`| Item | Status | Notes |`)
      lines.push(`|------|--------|-------|`)
      analysis.checklistReview.forEach((item) => {
        lines.push(`| ${item.item} | ${item.status} | ${item.notes} |`)
      })
      lines.push(``)
    }

    lines.push(`---`)
    lines.push(`*Generated by Product Discovery Tool*`)

    return lines.join('\n')
  }

  const generateJSON = () => {
    return JSON.stringify({
      sessionTitle: analysis.sessionTitle,
      exportedAt: new Date().toISOString(),
      analysisDate: analysis.createdAt,
      objectiveScore: analysis.objectiveScore,
      summary: analysis.summary,
      assumptions: analysis.assumptions,
      evidenceBacked: analysis.evidenceBacked,
      validationRecommendations: analysis.validationRecommendations,
      constraintAnalysis: analysis.constraintAnalysis,
      checklistReview: analysis.checklistReview,
    }, null, 2)
  }

  const handleCopyMarkdown = async () => {
    await navigator.clipboard.writeText(generateMarkdown())
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  const handleDownloadMarkdown = () => {
    const content = generateMarkdown()
    const blob = new Blob([content], { type: 'text/markdown' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `${analysis.sessionTitle.replace(/[^a-z0-9]/gi, '_')}_analysis.md`
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
  }

  const handleDownloadJSON = () => {
    const content = generateJSON()
    const blob = new Blob([content], { type: 'application/json' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `${analysis.sessionTitle.replace(/[^a-z0-9]/gi, '_')}_analysis.json`
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
  }

  return (
    <>
      <Button variant="outline" onClick={() => setShowDialog(true)}>
        Export
      </Button>

      <Dialog open={showDialog} onOpenChange={setShowDialog}>
        <DialogContent className="max-w-md">
          <DialogHeader>
            <DialogTitle>Export Analysis</DialogTitle>
          </DialogHeader>
          <div className="space-y-4 pt-4">
            <div className="space-y-2">
              <p className="text-sm text-muted-foreground">
                Export your analysis results to share with your team or save for reference.
              </p>
            </div>

            <div className="grid grid-cols-2 gap-3">
              <Button
                variant="outline"
                className="h-20 flex flex-col gap-1"
                onClick={handleCopyMarkdown}
              >
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  width="20"
                  height="20"
                  viewBox="0 0 24 24"
                  fill="none"
                  stroke="currentColor"
                  strokeWidth="2"
                  strokeLinecap="round"
                  strokeLinejoin="round"
                >
                  <rect width="14" height="14" x="8" y="8" rx="2" ry="2" />
                  <path d="M4 16c-1.1 0-2-.9-2-2V4c0-1.1.9-2 2-2h10c1.1 0 2 .9 2 2" />
                </svg>
                <span className="text-xs">
                  {copied ? 'Copied!' : 'Copy to Clipboard'}
                </span>
              </Button>

              <Button
                variant="outline"
                className="h-20 flex flex-col gap-1"
                onClick={handleDownloadMarkdown}
              >
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  width="20"
                  height="20"
                  viewBox="0 0 24 24"
                  fill="none"
                  stroke="currentColor"
                  strokeWidth="2"
                  strokeLinecap="round"
                  strokeLinejoin="round"
                >
                  <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" />
                  <polyline points="7 10 12 15 17 10" />
                  <line x1="12" x2="12" y1="15" y2="3" />
                </svg>
                <span className="text-xs">Download .md</span>
              </Button>

              <Button
                variant="outline"
                className="h-20 flex flex-col gap-1 col-span-2"
                onClick={handleDownloadJSON}
              >
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  width="20"
                  height="20"
                  viewBox="0 0 24 24"
                  fill="none"
                  stroke="currentColor"
                  strokeWidth="2"
                  strokeLinecap="round"
                  strokeLinejoin="round"
                >
                  <path d="M14.5 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V7.5L14.5 2z" />
                  <polyline points="14 2 14 8 20 8" />
                </svg>
                <span className="text-xs">Download .json (for integrations)</span>
              </Button>
            </div>
          </div>
        </DialogContent>
      </Dialog>
    </>
  )
}
